<a href="https://colab.research.google.com/github/surajit0609/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
## 1D array implementaion
ar=np.array([3,4,5,6])
ar

array([3, 4, 5, 6])

In [6]:
## 2D array implementation
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# Creating an array from tuple
tup = np.array((1, 3, 2))
tup

array([1, 3, 2])

In [22]:
##Accessing the array Index
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
arr
# Printing a range of Array
# with the use of slicing method
slcing_arry=arr[:2, ::2]
slcing_arry
# specific Indices
Index_arr = arr[[1, 1, 0, 3], 
                [3, 2, 1, 0]]
Index_arr


array([0., 6., 2., 3.])

In [ ]:
# ##Basic Array Operations
arry1=np.array([[1,2,3,7],
               [4,6,7,8]])
arry2=np.array([[1,2,3,7],
               [4,6,7,8]])
print(arry1+1)
print(arry1.sum())
print(arry1+arry2)

In [5]:
#####Data Types in Numpy
import numpy as np
x=np.array([1,2,3])
print(x.dtype)
x=np.array(["surajit","rahul"])
print(x.dtype)


int64
<U7


In [ ]:
##Math Operations on DataType array
arry1=np.array([[1,2,5],[3,6,9]],dtype=np.float)
print(arry1)
# sum=np.sum(arry1)
# sum
squar=np.sqrt(arry1)
squar

In [12]:
## shape 
import numpy as np

sample_array = np.array([[0, 4, 2],
					[3, 4, 5],
					[23, 4, 5],
					[2, 34, 5],
					[5, 6, 7]])

print("shape of the array :",
	sample_array.shape)


shape of the array : (5, 3)


In [16]:
## fromiter
#Import numpy module
import numpy as np

# iterable
iterable = (a*a for a in range(8))
arr = np.fromiter(iterable, float)
print("fromiter() array :",arr)


fromiter() array : [ 0.  1.  4.  9. 16. 25. 36. 49.]


In [19]:
## fromiter use
var="geekforgeek"
shap=np.fromiter(var, dtype = 'U2')
shap

array(['g', 'e', 'e', 'k', 'f', 'o', 'r', 'g', 'e', 'e', 'k'], dtype='<U2')

In [ ]:
##numpy.arange():
np.arange(1,20,2, dtype = np.float32)

In [ ]:
### empty
np.empty([4,3])

In [24]:
### one
np.ones([4,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
##numpy.arange() in Python
import numpy as np
print( np.arange(4).reshape(2, 2) )

[[0 1]
 [2 3]]


In [35]:
###numpy.zeros() in Python
np.zeros([2,2],dtype = int)
np.zeros(2,dtype=int)

array([0, 0])

In [ ]:
##numpy.linspace() in Python
np.linspace(1,2,10)
# Graphical Representation of numpy.linspace()
import numpy as geek
import pylab as p

# Start = 0
# End = 2
# Samples to generate = 10
x1 = geek.linspace(0, 2, 10, endpoint = True)
y1 = geek.ones(10)

p.plot(x1, y1, '*')
p.xlim(-0.2, 1.8)


In [41]:
## numpy.eye() in Python
np.eye(2,dtype=int)
np.eye(4,5,k=-1,dtype=int)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [45]:
####How to create an empty and a full NumPy array?
# empa = np.empty((3, 4), dtype=int)
# print("Empty Array")
# print(empa)
np.full((3,4),55,dtype=int)

array([[55, 55, 55, 55],
       [55, 55, 55, 55],
       [55, 55, 55, 55]])