<a href="https://colab.research.google.com/github/surajit0609/numpy/blob/main/NumPy_Array_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
#view in numpy
import numpy as np
arr=np.array([1,2,3,4,5])
v=arr.view()
print(id(v))
print(id(arr))
v[0]=67
print(arr)
print(v)

139941734419696
139941734868432
[67  2  3  4  5]
[67  2  3  4  5]


In [9]:
### copy
arra=np.array((1,2,5,7,9))
v=arra.copy()
print(id(v))
print(id(arra))
v[2]=89
print(arra)
print(v)

140238844884336
140238844963408
[1 2 5 7 9]
[ 1  2 89  7  9]


In [10]:
## Array Owning it’s Data
import numpy as np

# creating array
arr = np.array([2, 4, 6, 8, 10])

# creating copy of array
c = arr.copy()

# creating view of array
v = arr.view()

# printing base attribute of copy and view
print(c.base)
print(v.base)


None
[ 2  4  6  8 10]


In [ ]:
####How to Copy NumPy array into another array?
## method 1
arr=np.array([1,2,3,4,5,6,7])
print("orignal arr:",arr)
copy=np.empty_like(arr)
copy[:]=arr
copy[1]=676
print(copy)
### method 2
newarry=np.copy(arr)
print(newarry)

In [20]:
######Appending values at the end of an NumPy array
####Appending a single value to a 1D array
arr=np.array([1,2,3,6,8,9])
newarr=np.append(arr,7)
print(newarr)
###Example 2 
arr1=np.array([1,2,3,5,7])
arr2=np.array([5,8,2,7,9])
newarr1=np.append(arr1,arr2)
print(newarr1)
###Appending values at the end of the n-dimensional array
arr3 = np.arange (1,13).reshape(2, 6)
col = np.arange(5, 11).reshape(1, 6)
arr3_col=np.append(arr3,col,axis=0)
arr3_col

[1 2 3 6 8 9 7]
[1 2 3 5 7 5 8 2 7 9]


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [ 5,  6,  7,  8,  9, 10]])

In [ ]:
###How to swap columns of a given NumPy array?
newarr = np.arange(12).reshape(3,4)
print(newarr)
## swap
newarr[:,[0,3]]= newarr[:,[3,0]]
print(newarr)

In [ ]:
####numpy.hstack() in Python
arr=np.arange(8)
arr1=np.arange(7)
arr1
new_arr=np.hstack((arr,arr1))
print(new_arr)
##2d arra
in_arr1 = np.array([[ 1, 2, 3], [ -1, -2, -3]] )
print ("1st Input array : \n", in_arr1) 
  
in_arr2 = np.array([[ 4, 5, 6], [ -4, -5, -6]] )
print ("2nd Input array : \n", in_arr2) 
  
# Stacking the two arrays horizontally
out_arr = np.hstack((in_arr1, in_arr2))
print ("Output stacked array :\n ", out_arr)

In [ ]:
###numpy.vstack() in python
# Python program explaining
# vstack() function

import numpy as geek

# input array
in_arr1 = geek.array([ 1, 2, 3] )
print ("1st Input array : \n", in_arr1)

in_arr2 = geek.array([ 4, 5, 6] )
print ("2nd Input array : \n", in_arr2)

# Stacking the two arrays vertically
out_arr = geek.vstack((in_arr1, in_arr2))
print ("Output vertically stacked array:\n ", out_arr)


In [ ]:
###Joining NumPy Array
### numpy.concatenate()
import numpy as np

array_1 = np.array([1, 2])
array_2 = np.array([3, 4])
array_new = np.concatenate((array_1, array_2))
print(array_new)
arr1=np.stack((array_1,array_2))
print(arr1)


In [41]:
###Numpy dstack() method
# import numpy
import numpy as np

gfg1 = np.array([1, 2, 3])
gfg2 = np.array([4, 5, 6])

# using numpy.dstack() method
print(np.dstack((gfg1, gfg2)))


[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
#####How to compare two NumPy arrays?
an_array = np.array([[1, 2], [3, 4]])
another_array = np.array([[1, 2], [3, 4]])
comp=an_array == another_array
newarr=comp.all()
print(newarr)
a = np.array([101, 99, 87])
b = np.array([897, 97, 111])
print("a>b")
print(np.greater(a,b))
print("a<b")
print(np.less(a,b))
print("a>=b")
print(np.greater_equal(a,b))
print("a<=b")
print(np.less_equal(a,b))

In [ ]:
###Find the union of two NumPy arrays
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([20, 40, 60, 80])
v=np.union1d(arr1, arr2)
v
# import library
import numpy as np

# Create a 2D numpy array
arr2D = np.array([[11, 11, 12, 11],
					[13, 11, 12, 11],
					[16, 11, 12, 11],
					[11, 11, 12, 11]])

print('Original Array :' ,
	arr2D, sep = '\n')

# Get unique rows from
# complete 2D-array by
# passing axis = 0 in
# unique function along
# with 2D-array
uniqueRows = np.unique(arr2D,
					axis = 0)

# print the output result
print('Unique Rows:',
	uniqueRows, sep = '\n')


In [51]:
####Numpy np.unique() method
# import numpy
import numpy as np

a = [1, 2, 2, 4, 3, 6, 4, 8]

# using np.unique() method
gfg = np.unique(a)

print(gfg)


[1 2 3 4 6 8]
